dependencies:
  # Platform components
  - name: astronomer
    condition: global.astronomer.enabled
  - name: nginx
    condition: global.nginx.enabled
  - name: grafana
    condition: global.grafana.enabled
  - name: prometheus
    condition: global.prometheus.enabled
  - name: alertmanager
    condition: global.alertmanager.enabled
  - name: elasticsearch
    condition: global.elasticsearch.enabled
  - name: kibana
    condition: global.kibana.enabled
  - name: fluentd
    condition: global.fluentd.enabled
  - name: kube-state
    condition: global.kubeState.enabled
  - name: nginx-es
    condition: global.nginx-es.enabled

  # Airflow chart is deployed by the platform
  - name: airflow
    condition: global.airflow.enabled
