################################
## NGINX-Elasticsearch Default backend deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ template "nginx.fullname" . }}-default-backend
  labels:
    tier: logging
    component: default-backend
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: {{ template "nginx.name" . }}
      component: default-backend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: {{ template "nginx.name" . }}
        component: default-backend
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Release.Name }}-default-backend
          image: {{ template "nginx.defaultBackend.image" . }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.ports.defaultBackendHTTP }}
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: {{ .Values.ports.defaultBackendHTTP }}
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
