################################
## NGINX-Elasticsearch ServiceAccount
#################################
{{- if .Values.global.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "nginx-es.fullname" . }}-ingress-controller
  labels:
    tier: logging
    chart: {{ template "nginx-es.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
