################################
## NGINX-Elasticsearch Network Policy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "nginx.fullname" . }}-client-policy
  labels:
    tier: logging
    component: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: client
spec:
  podSelector:
    matchLabels:
      tier: logging
      component: nginx-es
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          tier: astronomer
          component: houston
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          tier: logging
          component: fluentd
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          tier: logging
          component: kibana
          release: {{ .Release.Name }}
    # - podSelector:
    #     matchLabels:
    #       tier: logging
    #       component: {{ template "elasticsearch.name" . }}
    #       release: {{ .Release.Name }}
    # - podSelector:
    #     matchLabels:
    #       tier: logging
    #       component: {{ template "elasticsearch.name" . }}-exporter
    #       release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          tier: airflow
          component: webserver
    ports:
    - protocol: TCP
      port: {{ .Values.common.ports.http }}
    - protocol: TCP
      port: {{ .Values.common.ports.transport }}
