################################
## NGINX-Elasticsearch Default backend service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ template "nginx-es.fullname" . }}-default-backend
  labels:
    tier: logging
    component: default-backend
    chart: {{ template "nginx-es.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    tier: logging
    component: default-backend
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ports.defaultBackendHTTP }}
      targetPort: {{ .Values.ports.defaultBackendHTTP }}
      protocol: TCP
      name: default-backend
