################################
## NGINX-Elasticsearch Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    tier: logging
    component: nginx-es
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # AWS annotations
    # XXX: Currently NLB has issues in EKS
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

    # Metrics annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.metrics | quote }}
spec:
  type: ClusterIP
  selector:
    tier: logging
    component: nginx-es
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.ports.https }}
      targetPort: {{ .Values.ports.https }}
      protocol: TCP
      name: https
    - port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
      protocol: TCP
      name: metrics
